spring.application.name=system_barbearia

# JWT
app.jwt.secret=bellator-barbearia-super-secret-key-2026
app.jwt.expiration=86400000
app.jwt.issuer=bellator-api

# CORS
app.cors.allowedOrigins=http://localhost:3000,http://localhost:5173

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:barbearia-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=bellator
spring.datasource.password=testbela

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# LOG SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true