spring.application.name=system_barbearia
server.port=${PORT:8080}
# JWT
app.jwt.secret=bellator-barbearia-super-secret-key-2026
app.jwt.expiration=86400000
app.jwt.issuer=bellator-api

# CORS
app.cors.allowedOrigins=http://localhost:3000,http://localhost:5173,http://localhost:8080,http://127.0.0.1:8080,*

# Banco H2
spring.datasource.url=jdbc:postgresql://dbbarbearia-1.cs1ooioewpp0.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=Lu4n5
spring.datasource.password=segura6022


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configurações de Email (SMTP Gmail)
# Lembre-se de substituir pelo seu email real e gerar uma Senha de Aplicativo no Google.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sistemabarbearias@gmail.com
spring.mail.password=svvgdsrykzixacyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
